#!/usr/bin/bash

#{{{ init
shopt -s extglob
nomods=true
volume=60
rate="$(xset q | grep "repeat rate")"
rate="${rate##* }"
lower=false
usage="Usage: $(basename $0) [OPTIONS]
  -m, --mods, --modifiers     do not ignore modifier keys
  -v, --vol, --volume NUM     sound volume, 1-100, default 60
  -r, --rate NUM              maximum number of sounds per second, defaults to keyrepeat rate
  -l, --lower, --lowercase    treat everything as lowercase (do not use key-caps.wav)
  -h, --help                  display this help
"

	#{{{ parameter parsing
for (( i=1; i <= $#; i++ )); do
	[ "${!i:0:1}" != "-" ] && { printf "$usage"; exit 2; }
	if [ "${!i:1:1}" = "-" ]; then

		#{{{ long parameters
		case "${!i}" in
			--modifiers | --mods)
				nomods=false
			;;
			--volume | --vol)
				i=$((i+1))
				volume="${!i}"
			;;
			--rate)
				i=$((i+1))
				rate="${!i}"
			;;
			--lower | --lowercase)
				lower=true
			;;
			--help)
				printf "$usage"
				exit
			;;
			*)
				printf "$usage"
				exit 2
			;;
		esac
		#}}}

	else

		#{{{ short parameters
		bumped=false
		case "${!i}" in
			*m*)
				nomods=false
			;;&
			*v*)
				[ "$bumped" = false ] && i=$((i+1)) && bumped=true
				volume="${!i}"
			;;&
			*r*)
				[ "$bumped" = false ] && i=$((i+1)) && bumped=true
				rate="${!i}"
			;;&
			*l*)
				lower=true
			;;&
			*h*)
				printf "$usage"
				exit 0
			;;
			!(-+([mvrl])))
				printf "$usage"
				exit 2
			;;
		esac
		#}}}

	fi
done
volume="$((65536*volume/100))"
rate="$(printf "$rate" | awk '{printf "%.3f", 1/$1}')"
	#}}}

cp -n "$(dirname "${BASH_SOURCE[0]}")"/*.wav /dev/shm/ || { printf "Unable to cache in /dev/shm!"; exit 1; }

	#{{{ keycode:sound mapping
declare -A sounds
while read a keycode b key c; do
	case "$key" in
		Control_[LR] | Alt_[LR] | Super_[LR])
			sounds[$keycode]="m"
		;;
		Shift_[LR])
			sounds[$keycode]="s"
		;;
		Return | KP_Enter)
			sounds[$keycode]="c"
		;;
		BackSpace | Delete)
			sounds[$keycode]="d"
		;;
		   Left |    Up |    Down |    Right |    Home |    End |    Prior |    Next |\
		KP_Left | KP_Up | KP_Down | KP_Right | KP_Home | KP_End | KP_Prior | KP_Next |\
		XF86ScrollUp | XF86ScrollDown)
			sounds[$keycode]="n"
		;;
	esac
done < <(xmodmap -pke)
	#}}}
#}}}

#{{{ main
play=true
shift=false
while read event; do
	if [ $play = true ]; then
		sleep "$rate" &
		waitpid=$!
	fi
	read line
	read line
	line="${line##* }"
	if [ "$event" = "EVENT type 14 (RawKeyRelease)" ]; then
		[ "${sounds[$line]}" = "s" ] && shift=false
		read -t0 || { wait $waitpid; play=true; }
		read line
		continue
	fi

	#{{{ play sound for keycode
	case "${sounds[$line]}" in
		c)
			[ $play = true ] && { paplay /dev/shm/key-confirm.wav --volume=$volume & } &>/dev/null
		;;
		d)
			[ $play = true ] && { paplay /dev/shm/key-delete.wav --volume=$volume & } &>/dev/null
		;;
		n)
			[ $play = true ] && { paplay /dev/shm/key-movement.wav --volume=$volume & } &>/dev/null
		;;
		s)
			shift=true
		;&
		m)
			[ $nomods = true ] && { read line; continue; }
		;&
		*)
			if [ $shift = true ] && [ "${sounds[$line]}" != "s" ] && [ $lower != true ]; then
				[ $play = true ] && { paplay /dev/shm/key-caps.wav --volume=$volume & } &>/dev/null
			else
				[ $play = true ] && { paplay /dev/shm/key-press-$(($RANDOM%4+1)).wav --volume=$volume & } &>/dev/null
			fi
		;;
	esac
	#}}}

	read -t0 && play=false || { wait $waitpid; play=true; }
	read line
done < <(xinput --test-xi2 --root | grep --line-buffered -A 2 -x -e "EVENT type 2 (KeyPress)" -e "EVENT type 14 (RawKeyRelease)")
#}}}
